# Trusty Beta requires sudo per https://docs.travis-ci.com/user/ci-environment/
sudo: required
dist: trusty

services:
  - docker

# We don't actually use anything java, but this feels the least jarring "language"
language: java

# Even though this shouldn't be needed, one build failed because of SSH known hosts:
# https://travis-ci.org/openzipkin/docker-zipkin/builds/78704161
addons:
  ssh_known_hosts: github.com

# Version tags are used to trigger these Travis CI runs
branches:
  only:
    - /^[0-9]+\.[0-9]+\.[0-9]+$/

# jq is used in release.sh to parse the responses of the quay.io API
install:
  - sudo wget https://github.com/stedolan/jq/releases/download/jq-1.5/jq-linux64 -O /usr/local/bin/jq
  - sudo chmod o+x /usr/local/bin/jq

before_script:
  # Log in to Docker Hub, needed to mirror images built on quay.io
  - docker login -u dockerzipkindeployer -p "$DOCKERHUB_PASSWORD"

script:
 # Also known as doit.sh
 - ./release.sh $TRAVIS_TAG

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/ead3c37d57527214e9f2
      - https://webhooks.gitter.im/e/e57478303f87ecd7bffc
    on_success: change
    on_failure: always

env:
  global:
    # The release process syncs minor and major version tags to the newly built subminor version tag
    # via the quay.io API, using these credentials.
    # travis encrypt QUAYIO_OAUTH2_TOKEN=from https://quay.io/organization/openzipkin?tab=applications
    - secure: "HXUMOI59TQDmVGfOpZByMXZ0x0R9tSFjxi49nYBmGz/SWV7FFBxnHF27xhDLRCQ1MMHLhHmuOvk35xtQurlGnKE44IRkNucFtU/Pgbc41ZRGKwYgflSXPGf9TzE/b2x3sx7eRWvsdolD/S31w8SXqQ78D5/+WovodK8wnqGhem1Vw/HE+nL+gQJDF3QygiMW0CpHF9WW3scoI8H5gnuPt6/LW4cmVHVDQlbM1kB/e+odBeEedv+t6MvwBQ2PWq3lUlNprPHrThYTEUnBq09GOAPm2mjONnK1fi1luD7nED+HNdRQbpwbc5OuTA45qLYyEsCY9jcDcvsZiFnX0HHcJ7TcHsHYUecSy0AVn6Hp1wxsjsuBk/XyY60m5cimsamufQCIz1ueThgiLhB7WUsw53QeWgRrK2NLYlWqXGH2/xhQ2H/WR34OQPNXNOQKTb635DcvwFTuocZzUJ9uOIdjQxFlQJ59e5RYnV1zVCCq7SoIbi5GBE1bp07ZD/C5yHABQgMdXFIhhNREcuYzRES883qv8XTDrdnCCDu/gNgJrZuM5cN4GuLs/alP3CL94oHjmJWvnXKheihclMjWrjfIttpFmaVXGNNMVhfSwyCyMKXQ/Zdvb1bLlB/jbTeQ+Dc3Nuz0o78C79N/z/HczeIG4l52SnSxfUaSwQxOG0VBzQ0="
    # The release process pushes images to Docker Hub, using these credentials
    # travis encrypt DOCKERHUB_PASSWORD=dockerzipkindeployer password from lastpass
    - secure: "H3JfhFIZs8i9GmpRR3Zjx74GrKtes600GL7uTNGgGCLfegYhGnYFdXETlMcbiezqi2n+DcHOp8r3g0xiV1UbCXjX4eJYgnSZYOBYjY6OFlwMOmsTWJQA4xcLJFI2BGd+Zed3BOHx07+mhaRRN934HYvsqTpgBQn8GJq8Qs4hrjbEAG5JWm8w9ebkFnDSUL5YZdV+jcpdq7j8pVGmvQz1RGia4M1TSOWld9OpRY1ABMrkUGo8f6Ew0wCXjPPOSsnCjVGo4POKTRbASN+KrBLiWlTg7MRWnkh8VeA6hUtWPvcZgIa9NQdHmew2D+ObY44BIhCiPsTc24wl1VyWVMXpb6yWGRTji/BR1olHqhnNfhBLwtb+gKJai+hS14l3Bm3OASBwl6d+2ec50LDSjXRNH15cSsQrv95v90YcJqDKX9yxURJk2zi146PqzF9y0/DoVPoky3Nsl7YmvbFgh6wzns+N6oL/RUmfgcdvzk06VcS2AiDl1Z5Vqy3bGtooLa1v47G1oHhyrJym/cJmkBPhrCY4iYc/nXPjfSrX5S84CRK3cNSviCjyGvbolAvDpdxglzjXqHLA5Su4Lj+dkuAdfbVEgsAGtT/HUzxyAhNtU2QWX66sg+/Krv2em9DcfAAgxkWFHtnfsFz3Qll46oF1euIgLLHiwJCQNy9sK83XMFE="
